version: "2"

services:

  latest:
    build:
      context: .
      dockerfile: ./latest/Dockerfile
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3040:80"
      - "3041:3306"
    tmpfs:
      - /var/lib/mysql
